# Code fo auto generating the gRPC files with code for for the defined message types and client and server code

build:
	protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative read.proto
